# Generated by Django 4.2.22 on 2025-07-16 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dept',
            new_name='Debt',
        ),
        migrations.RenameField(
            model_name='expenseshare',
            old_name='owned_amount',
            new_name='share_amount',
        ),
        migrations.CreateModel(
            name='ExpensePayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payers', to='expenses.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_payers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
