# Generated by Django 4.2.22 on 2025-07-16 20:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0002_rename_dept_debt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='paid_by',
        ),
        migrations.AlterUniqueTogether(
            name='expensepayer',
            unique_together={('expense', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='expenseshare',
            unique_together={('expense', 'user')},
        ),
    ]
